### ISSUE TITLE
Player starts at 0,0,0 origin in some rare occasions

### ISSUE THREAD

**Issue by Lunreth** [dysphie/nmrih-guaranteedspawn#2]
I think this line of the plugin forces clients to teleport at origin 0,0,0 in some maps and some rare occasions, not sure why but just good to know for future updates

https://github.com/dysphie/nmrih-guaranteedspawn/blob/2ff8aa68a407ac35777f2869fdb89a64e751edd2/scripting/nmrih-guaranteedspawn.sp#L418

**Comment by dysphie** [comment]
Speculative fix in 1.0.9

**Comment by dysphie** [comment]
No indication of this happening on any other server running the plugin, assuming solved/unrelated.
